close

for counter=1:24
    figure
    title(sprintf("Condition %02d", counter));
    fileName = sprintf("batteries_bak_%02d.mat", counter);
    importfile(fileName);

    counter2 = 0;
    for unit=batteries
        counter2 = counter2 + 1;
        unit1 = unit{1};
    
        if isempty(unit1)
    %         disp("Empty");
        else
    %         disp("Not empty")

            plot(unit1.Cycle, unit1.Discharge_Ah, '-'); hold on;
        end
    end

%     title(sprintf("Condition %02d", counter));

end




function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 13-Jan-2023 22:47:30

% Import the file
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
end
